### ISSUE TITLE
android26.jar compile err

### ISSUE THREAD

**Issue by DarkSherlock** [anggrayudi/android-hidden-api#52] opened 2018-11-28 10:02 UTC
Could not resolve all files for configuration ':app:androidApis'.
Failed to transform file 'android.jar' to match attributes {artifactType=android-mockable-jar, returnDefaultValues=false} using transform MockableJarTransform

studio show this error message when i replace the android.jar of android-26

**Comment by anggrayudi** [comment] 2018-12-05 16:43
This issue comes since Android Studio v3.2. I have no idea for the solution.

**Comment by anggrayudi** [comment] 2018-12-05 17:10
Closed as duplicate of #46

**Closed by anggrayudi** 2018-12-05 17:10 UTC
